// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    const webApiKey = String.fromEnvironment('webApiKey');
    const iosApiKey = String.fromEnvironment('iosApiKey');

    return const FirebaseOptions(
      apiKey: kIsWeb ? webApiKey : iosApiKey,
      appId: String.fromEnvironment('appId'),
      messagingSenderId: '',
      projectId: String.fromEnvironment('projectId'),
      authDomain: String.fromEnvironment('authDomain'),
      storageBucket: String.fromEnvironment('storageBucket'),
    );
  }
}
