name: micons_cli
description: The oficial CLI for icons.meedu.app
version: 0.0.5
homepage: https://icons.meedu.app

environment:
  sdk: ">=2.19.6 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  archive: ^3.3.7
  args: ^2.4.0
  crypto: ^3.0.2
  dcli: ^1.36.0
  encrypt: ^5.0.1
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  jwt_decode: ^0.3.1
  meedu: ^8.0.2
  path: ^1.8.3


executables:
  micons: micons