name: micons_cli
description: The oficial CLI for icons.meedu.app
version: 0.0.13
homepage: https://icons.meedu.app

environment:
  sdk: ">=3.2.0 <4.0.0"


dependencies:
  archive: ^3.4.10
  args: ^2.4.2
  dcli: ^6.0.5
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.8.1
  jwt_decode: ^0.3.1
  meedu: ^9.1.0
  path: ^1.8.3


dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.5.0
  json_serializable: ^6.7.1
  lints: ^4.0.0
  test: ^1.21.0


executables:
  micons: micons