name: micons_cli
description: The oficial CLI for icons.meedu.app
version: 0.0.8
homepage: https://icons.meedu.app

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  archive: ^3.3.7
  args: ^2.4.0
  dcli: ^3.1.0
  freezed_annotation: ^2.2.0
  http: ^1.1.0
  json_annotation: ^4.8.0
  jwt_decode: ^0.3.1
  meedu: ^9.0.0
  path: ^1.8.3


dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^3.0.0
  test: ^1.21.0


executables:
  micons: micons